from __future__ import annotations

from context_bridge.engram.payloads import (
    build_mem_save_payload,
    topic_key_from_graph_node,
    topic_key_from_parts,
)
from context_bridge.graph.models import GraphNode


def test_topic_key_from_parts_is_deterministic():
    a = topic_key_from_parts("layer", "API Layer")
    b = topic_key_from_parts("layer", "API Layer")
    assert a == b
    assert a.startswith("cb-")


def test_topic_key_from_parts_respects_max_len():
    long_text = "x" * 200
    key = topic_key_from_parts("hub", long_text, max_len=64)
    assert len(key) <= 64


def test_topic_key_from_parts_different_inputs_differ():
    a = topic_key_from_parts("layer", "api")
    b = topic_key_from_parts("layer", "service")
    assert a != b


def test_topic_key_from_graph_node_uses_id():
    node = GraphNode(id="node-1", path="src/x.ts")
    key = topic_key_from_graph_node(node)
    assert key == topic_key_from_parts("node", "node-1")


def test_build_mem_save_payload_content_format():
    payload = build_mem_save_payload(
        title="Architecture layer: API",
        type_="architecture",
        what="42 nodes in API layer",
        why="Synced from Understand Anything",
        where=".understand-anything/knowledge-graph.json#layer:api",
        learned="Generated by context-bridge sync",
        topic_key="cb-layer-api",
        project="demo",
    )
    assert payload.content == (
        "**What**: 42 nodes in API layer\n"
        "**Why**: Synced from Understand Anything\n"
        "**Where**: .understand-anything/knowledge-graph.json#layer:api\n"
        "**Learned**: Generated by context-bridge sync"
    )
    assert payload.topic_key == "cb-layer-api"
    assert payload.project == "demo"


def test_build_mem_save_payload_omits_learned_when_empty():
    payload = build_mem_save_payload(
        title="t",
        type_="architecture",
        what="w",
        why="y",
        where="z",
        topic_key="cb-t",
    )
    assert "**Learned**" not in payload.content


def test_content_hash_stable_for_same_payload():
    p1 = build_mem_save_payload(title="t", type_="a", what="w", why="y", where="z", topic_key="cb-t")
    p2 = build_mem_save_payload(title="t", type_="a", what="w", why="y", where="z", topic_key="cb-t")
    assert p1.content_hash == p2.content_hash


def test_content_hash_changes_with_content():
    p1 = build_mem_save_payload(title="t", type_="a", what="w1", why="y", where="z", topic_key="cb-t")
    p2 = build_mem_save_payload(title="t", type_="a", what="w2", why="y", where="z", topic_key="cb-t")
    assert p1.content_hash != p2.content_hash


def test_what_field_truncated_to_500_chars():
    payload = build_mem_save_payload(
        title="t", type_="a", what="x" * 600, why="y", where="z", topic_key="cb-t"
    )
    assert len(payload.what) == 500
