from __future__ import annotations

from context_bridge.engram.payloads import MemSavePayload, topic_key_from_parts
from context_bridge.graph.models import KnowledgeGraph
from context_bridge.graph.queries import nodes_by_domain
from context_bridge.sync.rules import DEFAULT_GRAPH_REF, SyncRules

MAPPER_TYPE = "domain"


def map_domains(
    graph: KnowledgeGraph,
    rules: SyncRules,
    *,
    project: str | None = None,
    graph_ref: str = DEFAULT_GRAPH_REF,
) -> list[MemSavePayload]:
    if not rules.domains.enabled:
        return []

    domains = nodes_by_domain(graph)
    payloads: list[MemSavePayload] = []
    for domain, nodes in domains.items():
        if len(nodes) < rules.domains.min_nodes:
            continue
        labels = [n.label or n.id for n in nodes][:5]
        what = f"{len(nodes)} nodes mapped to the '{domain}' business domain: {', '.join(labels)}."

        payloads.append(
            MemSavePayload(
                title=f"Domain: {domain}",
                type=MAPPER_TYPE,
                topic_key=topic_key_from_parts("domain", domain, prefix=rules.topic_key_prefix),
                what=what[:500],
                why="Synced from Understand Anything knowledge graph (domain view).",
                where=f"{graph_ref}#domain:{domain}",
                learned="Generated by context-bridge sync.",
                project=project,
            )
        )
    return payloads
