from __future__ import annotations

from context_bridge.engram.payloads import MemSavePayload, topic_key_from_parts
from context_bridge.graph.models import KnowledgeGraph
from context_bridge.graph.queries import hub_nodes
from context_bridge.sync.rules import DEFAULT_GRAPH_REF, SyncRules

MAPPER_TYPE = "codebase-map"


def map_hubs(
    graph: KnowledgeGraph,
    rules: SyncRules,
    *,
    project: str | None = None,
    graph_ref: str = DEFAULT_GRAPH_REF,
) -> list[MemSavePayload]:
    if not rules.hubs.enabled:
        return []

    hubs = hub_nodes(graph, min_degree=rules.hubs.min_degree, limit=rules.hubs.max_nodes)
    payloads: list[MemSavePayload] = []
    for hub in hubs:
        node = hub.node
        label = node.label or node.id
        location = node.path or node.id
        what = f"{label} has connection degree {hub.degree} — a central node in the dependency graph."
        if node.summary:
            what += f" {node.summary}"

        payloads.append(
            MemSavePayload(
                title=f"Entry point: {label}",
                type=MAPPER_TYPE,
                topic_key=topic_key_from_parts("hub", node.id, prefix=rules.topic_key_prefix),
                what=what[:500],
                why="Synced from Understand Anything knowledge graph (high-degree node).",
                where=f"{graph_ref}#node:{node.id} ({location})",
                learned="Generated by context-bridge sync.",
                project=project,
            )
        )
    return payloads
