from __future__ import annotations

from context_bridge.engram.payloads import MemSavePayload, topic_key_from_parts
from context_bridge.graph.models import KnowledgeGraph
from context_bridge.graph.queries import nodes_by_layer
from context_bridge.sync.rules import DEFAULT_GRAPH_REF, SyncRules

MAPPER_TYPE = "architecture"


def map_layers(
    graph: KnowledgeGraph,
    rules: SyncRules,
    *,
    project: str | None = None,
    graph_ref: str = DEFAULT_GRAPH_REF,
) -> list[MemSavePayload]:
    if not rules.layers.enabled:
        return []

    layers = nodes_by_layer(graph, min_nodes=rules.layers.min_nodes)
    payloads: list[MemSavePayload] = []
    for layer, nodes in layers.items():
        sample_paths = [n.path for n in nodes if n.path][:5]
        what = f"{len(nodes)} nodes in the '{layer}' layer."
        if sample_paths:
            what += f" Includes: {', '.join(sample_paths)}."

        payloads.append(
            MemSavePayload(
                title=f"Architecture layer: {layer}",
                type=MAPPER_TYPE,
                topic_key=topic_key_from_parts("layer", layer, prefix=rules.topic_key_prefix),
                what=what[:500],
                why="Synced from Understand Anything knowledge graph.",
                where=f"{graph_ref}#layer:{layer}",
                learned="Generated by context-bridge sync.",
                project=project,
            )
        )
    return payloads
