from __future__ import annotations

from context_bridge.engram.payloads import MemSavePayload, topic_key_from_parts
from context_bridge.graph.models import KnowledgeGraph
from context_bridge.sync.rules import DEFAULT_GRAPH_REF, SyncRules

MAPPER_TYPE = "architecture"


def map_tours(
    graph: KnowledgeGraph,
    rules: SyncRules,
    *,
    project: str | None = None,
    graph_ref: str = DEFAULT_GRAPH_REF,
) -> list[MemSavePayload]:
    """Map guided tours (`metadata.tours`) into architecture-summary memories.

    Understand Anything's guided-tour schema is not yet stable; this mapper
    is best-effort and silently skips entries that don't look like a tour.
    """
    if not rules.tours.enabled:
        return []

    tours_raw = graph.metadata.get("tours")
    if not isinstance(tours_raw, list):
        return []

    payloads: list[MemSavePayload] = []
    for tour in tours_raw[: rules.tours.max_tours]:
        if not isinstance(tour, dict):
            continue
        title = tour.get("title") or tour.get("name")
        if not title:
            continue
        summary = tour.get("summary") or tour.get("description") or ""
        steps = tour.get("steps")
        what = summary or f"Guided tour with {len(steps)} steps." if isinstance(steps, list) else summary

        payloads.append(
            MemSavePayload(
                title=f"Guided tour: {title}",
                type=MAPPER_TYPE,
                topic_key=topic_key_from_parts("tour", title, prefix=rules.topic_key_prefix),
                what=(what or "Guided tour generated by Understand Anything.")[:500],
                why="Synced from Understand Anything guided tours.",
                where=f"{graph_ref}#tours",
                learned="Generated by context-bridge sync.",
                project=project,
            )
        )
    return payloads
